export const PDF_MIME_TYPE = 'application/pdf';
export const PDF_EXTENSIONS = ['.pdf'];

export const DEFAULT_MAX_FILE_SIZE = Infinity; // 2GB
export const MAX_FILES = 100;

export const PDF_ERROR_CODES = {
    PROCESSING_CANCELLED: 'PROCESSING_CANCELLED',
    PROCESSING_FAILED: 'PROCESSING_FAILED',
    PDF_ENCRYPTED: 'PDF_ENCRYPTED',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    INVALID_OPTIONS: 'INVALID_OPTIONS',
    MEMORY_LIMIT_EXCEEDED: 'MEMORY_LIMIT_EXCEEDED',
};
