export const METADATA_FIELDS = {
    TITLE: 'title',
    AUTHOR: 'author',
    SUBJECT: 'subject',
    KEYWORDS: 'keywords',
    CREATOR: 'creator',
    PRODUCER: 'producer',
    CREATION_DATE: 'creationDate',
    MODIFICATION_DATE: 'modificationDate'
};

export const METADATA_PROFILES = {
    BASIC: 'basic',
    PRIVACY: 'privacy',
    FULL_CLEAN: 'full-clean'
};

export const METADATA_CLEANUP_OPTIONS = {
    [METADATA_PROFILES.BASIC]: [
        METADATA_FIELDS.AUTHOR,
        METADATA_FIELDS.SUBJECT,
        METADATA_FIELDS.KEYWORDS,
    ],
    [METADATA_PROFILES.PRIVACY]: [
        METADATA_FIELDS.TITLE,
        METADATA_FIELDS.AUTHOR,
        METADATA_FIELDS.SUBJECT,
        METADATA_FIELDS.KEYWORDS,
        METADATA_FIELDS.CREATOR,
        METADATA_FIELDS.PRODUCER
    ],
    [METADATA_PROFILES.FULL_CLEAN]: [
        METADATA_FIELDS.TITLE,
        METADATA_FIELDS.AUTHOR,
        METADATA_FIELDS.SUBJECT,
        METADATA_FIELDS.KEYWORDS,
        METADATA_FIELDS.CREATOR,
        METADATA_FIELDS.PRODUCER,
        METADATA_FIELDS.CREATION_DATE,
        METADATA_FIELDS.MODIFICATION_DATE
    ]
};
