export const PDF_SECURITY_ERROR_CODES = {
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
    DECRYPTION_FAILED: 'DECRYPTION_FAILED',
    PERMISSIONS_ERROR: 'PERMISSIONS_ERROR',
    INVALID_SECURITY_OPTIONS: 'INVALID_SECURITY_OPTIONS',
};

export const ENCRYPTION_ALGORITHMS = {
    AES_128: 'AES_128',
    AES_256: 'AES_256',
    RC4_40: 'RC4_40',
    RC4_128: 'RC4_128',
};

export const PERMISSION_FLAGS = {
    PRINT: 0x04,
    MODIFY_CONTENTS: 0x08,
    COPY: 0x10,
    MODIFY_ANNOTATIONS: 0x20,
    FILL_FORM: 0x100,
    COPY_FOR_ACCESSIBILITY: 0x200,
    ASSEMBLE_DOCUMENT: 0x400,
    HIGH_QUALITY_PRINT: 0x800,
};
